import type { UsageNotes } from '../types';

export interface RunStatusCopy {
  label: string;
  detail: string;
  tone: 'mock' | 'api' | 'fallback';
}

export function getRunStatusCopy(usageNotes: Pick<UsageNotes, 'mode' | 'model'>): RunStatusCopy {
  if (usageNotes.mode === 'api') {
    return {
      label: 'Live AI',
      detail: `Generated by the real model API: ${usageNotes.model}.`,
      tone: 'api',
    };
  }

  if (usageNotes.mode === 'api-fallback') {
    return {
      label: 'Fallback mock',
      detail: `API was unavailable, so the app used a stable mock result instead: ${usageNotes.model}.`,
      tone: 'fallback',
    };
  }

  return {
    label: 'Mock demo',
    detail: 'No real AI request was sent. This is the stable no-token-cost demo mode.',
    tone: 'mock',
  };
}
